"""
agent_runner.py
===============

A thin ReAct/function-calling loop that lets an Ollama model
use three “tools”:

1. fetch_html        (from tools.mlp)
2. fetch_pdf_as_text (from tools.mlp)
3. embed_text        (simple cosine wrapper inside)
4. save_similarity_csv (tools.mcp)
5. save_tex_file        (tools.mcp)

The agent will:

• iterate over URL list generated by `JobSearchAgent`
• compute both similarity scores
• persist CSV
• on user command, produce a tailored résumé and save .tex
"""

from __future__ import annotations
import pathlib, hashlib
import numpy as np
import requests

from tools import agent_tools as tools  # MCP‑registered helpers

# --------------------------------------------------------------------------- #
#  Small local helper                                                         #
# --------------------------------------------------------------------------- #
def embed_text(text: str) -> list[float]:
    return tools.embed_text(text)["vector"]


# --------------------------------------------------------------------------- #
#  Agent loop                                                                 #
# --------------------------------------------------------------------------- #
def run_agent(url_rows: list[dict], resume_pdf: pathlib.Path) -> list[dict]:
    resume_text = tools.fetch_pdf_as_text(str(resume_pdf))["text"]
    resume_vec  = embed_text(resume_text)

    ranked = []
    for row in url_rows:
        jd_clean = tools.fetch_html(row["url"])["html"]  # simplistic: no tag stripping
        jd_vec   = embed_text(jd_clean)

        embed_score = float(np.dot(resume_vec, jd_vec) /
                            (np.linalg.norm(resume_vec) *
                             np.linalg.norm(jd_vec) + 1e-8))

        # --- LLM-judged score ------------------------------------------------
        prompt = (
            "Rate how well the résumé matches the job description. "
            "Return only a number 0-1 with one decimal.\n\n"
            f"RÉSUMÉ:\n{resume_text[:2000]}\n\n---\n"
            f"JOB DESCRIPTION:\n{jd_clean[:2000]}"
        )
        r = requests.post(
            f"{OLLAMA_HOST}/api/chat",
            json={"model": LLM_MODEL,
                  "messages": [{"role": "user", "content": prompt}],
                  "stream": False},
            timeout=60,
        )
        r.raise_for_status()
        llm_score = float(r.json()["message"]["content"].strip().split()[0])

        row.update(
            embed_score=round(embed_score, 2),
            llm_score=round(llm_score, 2),
            job_id=hashlib.sha1(row["url"].encode()).hexdigest()[:12],
        )
        ranked.append(row)

    ranked.sort(key=lambda x: (x["llm_score"], x["embed_score"]),
                reverse=True)
    tools.save_similarity_csv(ranked)
    return ranked